language: node_js
os:
  - linux
  - osx
before_script:
  - 'npm install'
  - 'npm test -- -R dot --check-leaks'
after_script:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage'
